# Generated by Django 4.2.7 on 2025-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lightning_address',
            field=models.CharField(blank=True, help_text='예: test@walletofsatoshi.com', max_length=255, null=True, verbose_name='라이트닝 지갑 주소'),
        ),
    ]
