# Generated by Django 4.2.7 on 2025-11-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_lightning_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usdt_address',
            field=models.CharField(blank=True, help_text='예: username@speed.app', max_length=255, null=True, verbose_name='USDT 지갑 주소'),
        ),
    ]
