# Generated by Django 4.2.7 on 2025-11-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecash_enabled',
            field=models.BooleanField(default=False, help_text='활성화하면 결제 페이지에서 e-cash 결제 옵션이 표시됩니다', verbose_name='e-cash 결제 허용'),
        ),
    ]
