# Generated by Django 4.2.7 on 2025-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', '현금'), ('lightning', '라이트닝')], max_length=20, verbose_name='결제 방법'),
        ),
    ]
