# Generated by Django 4.2.7 on 2025-08-04 15:13

from django.db import migrations
from django.contrib.auth import get_user_model


def assign_missing_created_by(apps, schema_editor):
    """created_by가 비어있는 상품에 사용자 지정"""
    Product = apps.get_model('products', 'Product')
    User = get_user_model()
    
    # Get products without created_by
    products_without_creator = Product.objects.filter(created_by__isnull=True)
    
    if products_without_creator.exists():
        # Get the first user (or create a default admin user)
        first_user = User.objects.first()
        if first_user:
            products_without_creator.update(created_by=first_user)
            print(f"created_by={first_user.username}로 업데이트된 상품 수: {products_without_creator.count()}개")
        else:
            print("사용자를 찾지 못해 created_by 없이 유지됩니다")


def reverse_assign_missing_created_by(apps, schema_editor):
    """역작업 - 상품의 created_by를 null로 설정"""
    # This is a data migration, reversal isn't strictly necessary
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.RunPython(assign_missing_created_by, reverse_assign_missing_created_by),
    ]
