# Generated by Django 4.2.7 on 2025-08-04 15:13

from django.db import migrations
from django.contrib.auth import get_user_model


def assign_missing_created_by(apps, schema_editor):
    """Assign created_by to products that don't have one"""
    Product = apps.get_model('products', 'Product')
    User = get_user_model()
    
    # Get products without created_by
    products_without_creator = Product.objects.filter(created_by__isnull=True)
    
    if products_without_creator.exists():
        # Get the first user (or create a default admin user)
        first_user = User.objects.first()
        if first_user:
            products_without_creator.update(created_by=first_user)
            print(f"Updated {products_without_creator.count()} products with created_by={first_user.username}")
        else:
            print("No users found - products will remain without created_by")


def reverse_assign_missing_created_by(apps, schema_editor):
    """Reverse operation - set created_by to null for products"""
    # This is a data migration, reversal isn't strictly necessary
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.RunPython(assign_missing_created_by, reverse_assign_missing_created_by),
    ]
