# Generated by Django 4.2.7 on 2025-11-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_regular_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', '현금'), ('lightning', '라이트닝'), ('ecash', 'e-cash')], max_length=20, verbose_name='결제 방법'),
        ),
    ]
